# Generated by Django 4.2.30 on 2026-04-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("ENTREE", "Entrée"), ("SORTIE", "Sortie")],
                        max_length=10,
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits.produit",
                    ),
                ),
            ],
        ),
    ]
