# Generated by Django 4.2.30 on 2026-05-05 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0004_produit_date_creation_produit_date_expiration_and_more"),
        ("stock", "0003_alter_mouvementstock_utilisateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouvementstock",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mouvements",
                to="produits.produit",
            ),
        ),
        migrations.CreateModel(
            name="SuggestionReapprovisionnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_suggeree", models.IntegerField()),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("BASSE", "Basse"),
                            ("NORMALE", "Normale"),
                            ("HAUTE", "Haute"),
                            ("CRITIQUE", "Critique"),
                        ],
                        default="NORMALE",
                        max_length=20,
                    ),
                ),
                ("raison", models.CharField(max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                ("traitee", models.BooleanField(default=False)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="produits.produit",
                    ),
                ),
            ],
            options={
                "ordering": ["-priorite", "-date_creation"],
            },
        ),
    ]
