# Generated by Django 4.2.30 on 2026-04-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="code_barre",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
