# Generated by Django 4.2.30 on 2026-05-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fournisseur", "0001_initial"),
        ("commandes", "0004_alter_commande_fournisseur"),
        ("produits", "0002_produit_code_barre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fournisseur.fournisseur",
            ),
        ),
        migrations.DeleteModel(
            name="Fournisseur",
        ),
    ]
