# Generated by Django 4.2.30 on 2026-05-05 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0003_alter_produit_fournisseur_delete_fournisseur"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produit",
            name="date_expiration",
            field=models.DateField(
                blank=True, help_text="Date de péremption du produit", null=True
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="date_modification",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="produit",
            name="date_obsolescence",
            field=models.DateField(
                blank=True, help_text="Date marquant l'obsolescence", null=True
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="statut_obsolescence",
            field=models.CharField(
                choices=[
                    ("ACTIF", "Actif"),
                    ("OBSOLETE", "Obsolète"),
                    ("DISCONTINU", "Discontinu"),
                ],
                default="ACTIF",
                max_length=20,
            ),
        ),
    ]
