# Generated by Django 4.2.30 on 2026-04-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commandes", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="utilisateur",
        ),
    ]
