# Generated by Django 4.2.30 on 2026-05-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fournisseur", "0001_initial"),
        ("commandes", "0003_remove_commande_utilisateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fournisseur.fournisseur",
            ),
        ),
    ]
