# Generated by Django 4.2.30 on 2026-05-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="utilisateur",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("GESTIONNAIRE", "Gestionnaire"),
                    ("EMPLOYE", "Employé"),
                ],
                default="EMPLOYE",
                max_length=20,
            ),
        ),
    ]
